---
- hosts: 127.0.0.1
  gather_facts: false
  sudo: true
  vars:
    enviroment: local

  tasks:

  - include: tasks.yml

  - name: Set local hostname
    hostname: name=local

  handlers:

  - include: handlers.yml